spring.application.name=reserba

itemconfig.name = item
itemconfig.value = milk


spring.datasource.url=jdbc:postgresql://localhost:5436/reserba
spring.datasource.username=postgres
spring.datasource.password=password

# This tells Hibernate not to interfere with Flyway
spring.jpa.hibernate.ddl-auto=validate

# Optional: specifically tell Flyway where to look
spring.flyway.locations=classpath:db/migration

# Force JPA to wait for Flyway
spring.flyway.enabled=true