spring.datasource.url=jdbc:postgresql://ep-patient-mountain-agbdj5i8-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ExNkRXCnb37u
server.port=8080